openapi: 3.0.0
info:
  version: "1.0.0"
  title: "Wspieram Przyrodę"
  license:
    name: "MIT"
servers:
  - url: https://api.wspieramprzyrode.pl/v1
    description: Main (production) server
  - url: https://api-staging.wspieramprzyrode.pl/v1
    description: Internal staging server for testing
  - url: https://api-dev.wspieramprzyrode.pl/v1
    description: Internal staging server for developers
tags:
  - name: inventory
    description: Inventory services
paths:
  /inventory/categories:
    get:
      summary: "Returns object category inventories"
      operationId: "GetObjectCategories"
      tags:
        - inventory
        - categories
      parameters: []
      responses:
        "200":
          $ref: "#/components/responses/ListOfObjectCategories"
    post:
      summary: Add a new inventory category
      operationId: "CreateObjectCategory"
      tags:
        - inventory
        - categories
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ObjectCategoryName'
            example:
              name: "Budka lęgowa"
      responses:
        "200":
          $ref: "#/components/schemas/ObjectId"
  /inventory/objects:
    get:
      tags:
        - inventory
        - objects
      summary: "Returns object inventories"
      description: "Returns list object in inventory"
      operationId: "GetObjects"
      parameters: []
      responses:
        "200":
          $ref: "#/components/responses/ListOfObjects"
    post:
      security:
        - bearerAuth: []
      tags:
        - inventory
        - objects
      summary: "Create inventory object"
      description: "add new object to inventory"
      operationId: "CreateObject"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateObject'
            example:
              category_id: "0353C229-9522-48BA-8EF3-854EFDDED212"
              coordinates:
                lat: 50.306472
                lng: 18.602258
      responses:
        "201":
          $ref: "#/components/schemas/ObjectId"
        "401":
          $ref: '#/components/responses/Unauthorized'
  /inventory/objects/{id}:
    get:
      tags:
        - inventory
        - objects
      summary: "Returns inventory object"
      description: "Returns details of object"
      operationId: "GetObjectByID"
      parameters:
        - in: path
          name: id
          description: Object ID
          required: true
          schema:
            type: string
          example:
            id: "96D0EE07-3EF9-426B-8E03-9475A3F70511"
      responses:
        "200":
          $ref: "#/components/responses/GetObject"
        "404":
          $ref: "#/components/responses/NotFound"
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
    ObjectCategoryId:
      type: string
      format: uuid
    ObjectCategoryName:
      type: string
    ObjectCategory:
      type: "object"
      title: Inventory Category
      required:
        - name
      properties:
        id:
          $ref: '#/components/schemas/ObjectCategoryId'
        name:
          $ref: '#/components/schemas/ObjectCategoryName'
    Coordinates:
      type: "object"
      title: Coordinates
      required:
        - lat
        - lng
      properties:
        lat:
          type: number
          format: float
        lng:
          type: number
          format: float
    ObjectId:
      type: string
      format: uuid
    Object:
      type: "object"
      title: Inventory object
      required:
        - category_id
        - coordinates
      properties:
        id:
          $ref: "#/components/schemas/ObjectId"
        category_id:
          $ref: '#/components/schemas/ObjectCategoryId'
        coordinates:
          $ref: "#/components/schemas/Coordinates"
    CreateObject:
      type: "object"
      title: Create object
      required:
        - category_id
        - coordinates
      properties:
        category_id:
          $ref: '#/components/schemas/ObjectCategoryId'
        coordinates:
          $ref: "#/components/schemas/Coordinates"
  responses:
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: 404
            message: resource not found
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    ListOfObjectCategories:
      description: List of inventory categories
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/ObjectCategory'
          example:
            - id: 58162552-24EA-40D5-B40A-664190D410BC
              name: Budka lęgowa
            - id: 0BDB9887-B9F2-4A34-BD6F-61A7E88C65D3
              name: Paśnik
            - id: 334C9697-58F0-4766-A86E-371D2BA1EE36
              name: Pomnik przyrody
    ListOfObjects:
      description: List of inventory objects
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Object'
          example:
            - id: 96D0EE07-3EF9-426B-8E03-9475A3F70511
              category_id: 58162552-24EA-40D5-B40A-664190D410BC
              coordinates:
                lat: 50.306472
                lng: 18.602258
            - id: 40749299-E630-4276-92A9-0856E449F19A
              category_id: 58162552-24EA-40D5-B40A-664190D410BC
              coordinates:
                lat: 50.306880
                lng: 118.604721
    GetObject:
      description: Get Object
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Object'
          example:
            id: 96D0EE07-3EF9-426B-8E03-9475A3F70511
            category_id: 58162552-24EA-40D5-B40A-664190D410BC
            coordinates:
              lat: 50.306472
              lng: 18.602258
